### ISSUE TITLE
Reference to old libxml causes problems on OSX 10.11.2

### ISSUE THREAD

**Issue by mccalluc** [movitto/RXSD#22]
Something has changed with the libxml dependency, so that when I try a `bundle install` under OSX 10.11.2, I get this error: 
```
An error occurred while installing libxml-ruby (2.4.0), and Bundler cannot continue.
Make sure that `gem install libxml-ruby -v '2.4.0'` succeeds before bundling.
```

I think the fix is easy:
```diff
-  s.add_dependency('libxml-ruby', '~> 2.4.0')
+  s.add_dependency('libxml-ruby', '~> 2.8.0')
```

With this tweak I can bundle install, and tests pass.

**Comment by movitto** [comment]
Hey @mccalluc thanks for the issue. Would you be able to send a PR? I don't actively maintain the codebase thesedays but would review & merge PRs. Also with this I'd bump the version and push a new update to rubygems (long overdue!)

Thanks,
  -Mo
